### ISSUE TITLE
Devlog missing Devlog

### ISSUE THREAD

**Issue by orionstein** [uglow/devlog#2]
Wouldn't it be appropriate to showcase the repo for a devlog project with it's own devlog.md file?

Just thought it was funny it didn't have one!

But this way, users can see the results of an example devlog once entries have been added, as well!

**Comment by orionstein** [comment]
Actually, on a more serious note, adapting this so it can write to a devlog in the current project folder is something I think could be helpful. That way, you can have a devlog.md file in the project that outlines the timeline of the project. Theoretically this could end up similar to commit messages, but it could be helpful for referencing decisions and direction over time, separate from a readme.

**Comment by uglow** [comment]
Hi @orionstein, thanks for the suggestion. I like the idea. The tool would try and use the `devlog.md` file in the current directory (if it exists) otherwise it fallback to the `~/devlog` directory (current behaviour). To create the file in the current directory, we could use `devlog here`. Thoughts?

**Comment by orionstein** [comment]
Hi @uglow, thanks! I would also suggest that you could streamline/enhance the user experience with this.

1. Running devlog with no flags
This would check for a `devlog.md` file in the current directory, and fallback to the global devlog, as you say. However, before the fallback, it could check for a readme.rm, or a .git folder in the current directory - if I was running this in a project directory, I would want it to create a devlog in that project, otherwise run it globally. If a readme or git repo exists, also generate the devlog file.
There are obviously times when you don't want it to think for you, which brings us to -

2. Simplified flags
Devlog could also be run with `devlog -g` or `devlog -l`. My thoughts here are to get the flags closer to npm/unix style cmd flags. `devlog -g` would always create/write to the global devlog, even if you were in a project folder. `devlog -l` would always create/write to a local directory devlog, even if it is not a project directory. This would give pretty complete control over where these were written, and make it quick/easy to start.

3. Git commit style message flag
The last idea is to add the ability to run git commit style messaging, with `devlog -m`. This way you don't drop into stdin, and it's just a oneshot command. `devlog -m 'Decided to add Bluebird'` would add the entry to the local or global devlog, depending on context. `devlog -gm 'Decided to add Bluebird'` would, as an example, always write that message directly to the global devlog.

I can try to look at prototyping some of those in my fork later. Busy, but wanted to explain/set out those ideas at least. Of course, these are all just suggestions, and feel free to improve, critique, or comment on any of them.

**Comment by uglow** [comment]
Thanks @orionstein . I plan to implement support for a folder-local devlogs in a backwards compatible way. This means:
- `devlog` will remain unchanged, always writing to the global log
- `devlog -l` will create/append-to a devlog.md file _in the current directory_ with stdin
- `devlog -m multi-word message without...` will write to devlog.md _in the current directory_ without going into stdin. Is it conventional to use quotes around the message?
